---
title: "02_neuron_morphology"
author: "Alexander Bates"
date: "`r Sys.Date()`"
output: html_document
---

# Tutorial 02: Neuron morphology

## Introduction

The purpose of this tutorial is to examine neuron morphology. 

We can visualise neurons, compare their morphological similarity with NBLAST, and plot them with their synapses.

To do this, we are going to look at one of the data 'subets' we have pre-prepared. 

You can change which subset and data set to examine, by changing these two variables:

```
```

But by default, let us look at the front leg neuropil! 

This is available for BANC, maleCNS and MANC.

## Read meta data

Let's start by reading the meta data for our chosen subset:

```
```

Let's now plot the neuron counts we have, by their super class:

```
```

That's quite a lot of neurons, but not too many.

Let's make a vector of their IDs.

```
```

## Read .swc file

A .swc file is a format for encoding neuron 'skeleton' structure.

We could work with high-resolution mesh data (not in our google bucket), but for most tasks a skeleton suffices and is faster.

If you would like to see how to read in mesh data for the BANC project, which enables nice visualisations, see [here](https://flyconnectome.github.io/bancr/reference/banc_read_neuron_meshes.html).

Let's just take one ID from our vector. We can read its .swc file straight from one of the .zip archives we have.

We can visualise it in BANC space, or in it's native space if not a BANC neuron. For non-BANC datasets we provide two spaces, because visualising everything in BANC space assists us with co-visualisation. We will see an example of this later.

For now, let's read and plot that neuron!

```
```

We can also use `rgl` to show the neuron in an interactive 3D window:

```
```

We can also use the `plotly` engine with the `natverse`:


```
```

## Read synapses

We can plot this neuron with its synapses.

To do this, let's fetch synapses from only this neuron, from the feather file in this subset. 

We only need columns `x`,`y`,`z`,`pre` and `post`. 

When our neuron is `==pre` we will set a new column `prepost` to `0`, to indicate it is an output synapse.

When our neuron is `==post` we will set a new column `prepost` to `1`, to indicate it is an input synapse.

We can plot input synapses in navy, and output in red:

```
```

## Read neuropil meshes

In our `obj` folder, we have some useful neuroaatomical objects!

Let's fetch both the BANC ventral nerve cord neuropil, and the leg neuropil.

We can show them over our neurons, with a little transparency.

```
```

## NBLAST

Now that we have seen how to visualise the skeleton of one neuron, let's grab all of our neurons from this neuropil and assess how similar they are.

To read, all the neurons, we can select just out subset from the `.zip` archive of all skeletons:

```
```

We can now convert them from 1. nm to um, and 2. to a 'dotprops' vector cloud, and use this to run an NBLAST!

```
```

Let's visualise the result as a dendrogram:

```
```

Great, now let's view ~20 clusters by morphology:


```
```

You can try playing wit the number of clusters, `k`.

Cool! What do you think all of these neurons do?

## New dataset

Let's repeat what we just did, but with the maleCNS dataset, and reading from the banc_space .zip

```
```

Now we can plot our neurons together with the BANC ones!

```
```

## Your Turn: New subset

Now try this analysis yourself with a different subset, e.g. antennal lobe


## Extention: axon-dendrite splits

For all of our datasets, except the BANC right now, we have axon-dendrite splits that have been pre-calculated.

This uses a graph theoretic algorithm from Schneider-Mizell et al. 2026 (see the paper [here]()).

The method relies on the idea that information runs from input to output synapses, and determines axon versus dendrites by "cutting" the neuron at its major information bottleneck, and observing which half has more input/output.

The `label` column in the underlying `.swc` files gives the compartment. 

In addition, the `pre_label` and `post_label` columns in our synapse tables give compartments.

Let's read in some maleCNS data, and visualise neurons. 

We will look at the neurons DNa01. To do this we must:

1. Read the meta file, filter for DNa01 on `cell_type`
2. Find its IDs, and read them from the `.swc` file `.zip` archive
3. Read these skeletons in, then subset by "label"
4. Visualise these compartments in different colors

Let's use four colours:

blue = dendrite
green = primary dendrite (linker)
orange = axon
purple = primary neurite tract (cell body fiber tract)

```
```

We can also see the synapses by this split. 

Let's read the .feather file in our data subset, and select just those synapses related to our neurons.

Let's use four colours:

navy = input synapse, dendrite
cyan = input synapse, axon
pink = output synapse, dendrite
red = output synapse, axon

```
````


Once you are done with 01, let's work on tutorial 02. I have similar scripts for working with morphologies with the natverse, here: /Users/abates/projects/natverse/nat.examples.
Please start by exploring this repository, to get a sense of the sort of plotting and NBLAST code we are going to want to employ. Also see: https://github.com/natverse/nat.ggplot?tab=readme-ov-file,
and https://github.com/natverse/nat.nblast. Now, look at the 02 .Rmd file I have made. I have laid out the plan for the tutorial. Can you fill in the code, and lightly update the test for consistency,
including helpful hyperlinks, and increased clarity. We want to have the same style as the 01 .Rmd file. We want to generally show the user how to make a rgl plot (plot3d) and plotly plots, and one example of a nat.ggplot. 
When looking for the leg neuropil obj file, use this regex search: "^LegNp\\(T1\\)|T1|^ProNM-T1|^LNp_T3". When you have the draft, execute the knit to html, observe errors, and correct based on observed errors. Remember we want images output to our images/ folder, as we had asked for tutorial 01.



























